const CARDS = [
  {
    id: 1,
    title: "Cake Shop",
    image: "https://via.placeholder.com/300",
    description: "A delicious chocolate cake with a rich flavor.",
    rating: 2.8,
    price: 15.99,
    promoPrice: 12.99,
  },
  {
    id: 2,
    title: "Cupcake Heaven",
    image: "https://via.placeholder.com/300",
    description: "Freshly baked cupcakes with various flavors.",
    rating: 4.6,
    price: 8.99,
    promoPrice: null,
  },
  {
    id: 3,
    title: "Bakery Delight",
    image: "https://via.placeholder.com/300",
    description: "Traditional bread and pastries made daily.",
    rating: 3.9,
    price: 12.49,
    promoPrice: 10.99,
  },
  {
    id: 1,
    title: "Cake Shop",
    image: "https://via.placeholder.com/300",
    description: "A delicious chocolate cake with a rich flavor.",
    rating: 2.8,
    price: 15.99,
    promoPrice: 12.99,
  },
  {
    id: 2,
    title: "Cupcake Heaven",
    image: "https://via.placeholder.com/300",
    description: "Freshly baked cupcakes with various flavors.",
    rating: 4.6,
    price: 8.99,
    promoPrice: null,
  },
  {
    id: 3,
    title: "Bakery Delight",
    image: "https://via.placeholder.com/300",
    description: "Traditional bread and pastries made daily.",
    rating: 3.9,
    price: 12.49,
    promoPrice: 10.99,
  },
  {
    id: 1,
    title: "Cake Shop",
    image: "https://via.placeholder.com/300",
    description: "A delicious chocolate cake with a rich flavor.",
    rating: 2.8,
    price: 15.99,
    promoPrice: 12.99,
  },
  {
    id: 2,
    title: "Cupcake Heaven",
    image: "https://via.placeholder.com/300",
    description: "Freshly baked cupcakes with various flavors.",
    rating: 4.6,
    price: 8.99,
    promoPrice: null,
  },
  {
    id: 3,
    title: "Bakery Delight",
    image: "https://via.placeholder.com/300",
    description: "Traditional bread and pastries made daily.",
    rating: 3.9,
    price: 12.49,
    promoPrice: 10.99,
  },
  {
    id: 1,
    title: "Cake Shop",
    image: "https://via.placeholder.com/300",
    description: "A delicious chocolate cake with a rich flavor.",
    rating: 2.8,
    price: 15.99,
    promoPrice: 12.99,
  },
  {
    id: 2,
    title: "Cupcake Heaven",
    image: "https://via.placeholder.com/300",
    description: "Freshly baked cupcakes with various flavors.",
    rating: 4.6,
    price: 8.99,
    promoPrice: null,
  },
  {
    id: 3,
    title: "Bakery Delight",
    image: "https://via.placeholder.com/300",
    description: "Traditional bread and pastries made daily.",
    rating: 3.9,
    price: 12.49,
    promoPrice: 10.99,
  },
];
